version: '3'

services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - nextjs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge